priem22/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

priem22/priem22/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('abit/', mainapp.abit, name='abit'),
    path('otchets/', mainapp.otchets, name='otchets'),
    path('add/', mainapp.add_abit, name='add'),
    path('edit/', mainapp.edit_abit, name='edit'),
    path('delete/', mainapp.main, name='main'),
    # path('delete/', mainapp.delete_abit, name='delete'),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

priem22/authapp/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django.dispatch import receiver
from django.db.models.signals import post_save


class User(AbstractUser):
    username = models.CharField(max_length=32, unique=True)
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст', default=18)

    activation_key = models.CharField(max_length=128, blank=True)

    def is_activation_key_expired(self):
        return now() - self.date_joined > timedelta(hours=48)


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'
    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж')
    )

    user = models.OneToOneField(
        User,
        unique=True,
        null=False,
        db_index=True,
        on_delete=models.CASCADE
    )

    tagline = models.CharField(verbose_name='тэги', max_length=128, blank=True)

    about_me = models.TextField(verbose_name='о себе', max_length=512, blank=True)

    gender = models.CharField(verbose_name='пол', max_length=1, choices=GENDER_CHOICES, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

priem22/authapp/forms.py
import hashlib
import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age', 'avatar', )

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды')

        return data

    # def save(self):
    #     user = super(UserRegisterForm, self).save()
    #
    #     user.is_active = False
    #     salt = hashlib.sha1(str(random.Random()).encode('utf8')).hexdigest()[:6]
    #     user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
    #     user.save()
    #     return user


class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды')

        return data


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('tagline', 'about_me', 'gender')

    def __init__(self, *args, **kwargs):
        super(UserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

priem22/authapp/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.urls import reverse
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages

from authapp.forms import UserLoginForm, UserRegisterForm, UserEditForm, UserProfileEditForm
from authapp.models import User
from django.db import transaction


def login(request):
    title = 'Вход'

    login_form = UserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))

    context = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'Регистрация'

    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
            # user = register_form.save()
            # if send_verify_mail(user):
            #     messages.add_message(request, messages.SUCCESS,
            #                          "Подтвердите регистрацию по ссылке из письма, которое отправленно на почту!")
            #     print('-------------------- Email sanded --------------------')
            #     return HttpResponseRedirect(reverse('auth:login'))
            # else:
            #     print('-------------------- Sending email ERROR! --------------------')
            #     return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = UserRegisterForm()

    context = {
        'title': title,
        'register_form': register_form
    }

    return render(request, 'authapp/register.html', context)


@transaction.atomic
def edit(request):
    title = 'Редактирование'

    if request.method == 'POST':
        edit_form = UserEditForm(request.POST, instance=request.user)

        # profile_form = UserProfileEditForm(request.POST, instance=request.user.userprofile)

        # if edit_form.is_valid() and profile_form.is_valid():
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = UserEditForm(instance=request.user)
        # profile_form = UserProfileEditForm(instance=request.user.userprofile)

    context = {
        'title': title,
        'edit_form': edit_form,
        # 'profile_form': profile_form,
    }

    return render(request, 'authapp/edit.html', context)


def send_verify_mail(user):
    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])

    title = f'Подтверждение учетной записи {user.username}'

    message = f'Для подтверждения учетной записи {user.username} на портале ' \
        f'{settings.DOMAIN_NAME} для акттивации учетной записи перейдите по ссылке:' \
        f'{settings.DOMAIN_NAME}{verify_link}'

    return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


def verify(request, email, activation_key):
    try:
        user = User.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            auth.login(request, user, backend='django.contrib.auth.backend.ModelBackrnd')
            return render(request, 'authapp/verification.html')
        else:
            print(f'error activation user: {user}')
            return render(request, 'authapp/verification.html')
    except Exception as e:
        print(f'error activation user: {e.args}')
        return HttpResponseRedirect(reverse('main'))

priem22/authapp/templates/authapp/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block css %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    {% endblock %}<title>{{ title|title }}</title>
</head>
<body>
<div class="container">
<div class="login">
<div class="h2 text-center head">
Вход в систему
</div>
{% block content %}
{% endblock %}
</div>
</div>
</body>
</html>

priem22/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
    <img src="/media/{{ user.avatar|default:'placeholder.png' }}" class="w-25">
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="POST" enctype=multipart/form-data>
        {% csrf_token %}
        {{ edit_form.as_p }}
        {{ profile_form.as_p }}
      <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
    <button class="btn btn-round form-control">
        <a href="{% url 'main' %}" class="">
            На Главную
        </a>
    </button>
{% endblock %}

priem22/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
<form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
    {% csrf_token %}
    {{ login_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="войти">
</form>
<button class="btn btn-round form-control">
    <a href="{% url 'auth:register' %}" class="">зарегистрироваться</a>
</button>
{% endblock %}

priem22/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="POST" enctype="multipart/form-data">>
        {% csrf_token %}
        {{ register_form.as_p }}
      <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
    <button class="btn btn-round form-control">
        <a href="{% url 'auth:login' %}" class="">Войти</a>
    </button>
{% endblock %}

priem22/authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
    {% if user %}
      <h3>Поздравляем!</h3>
      <br>
      <h4>Пользователь {{user.username}} подтвержден.</h4>
    {% else %}
      <h3>Верификация не пройдена.</h3>
    {% endif %}
    <br>
    <button class="btn btn-round form-control">
      <a href="{% url 'main' %}" class="">на главную</a>
    </button>

{% endblock %}