priem22/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

priem22/priem22/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('abit/', mainapp.abit, name='abit'),
    path('otchets/', mainapp.otchets, name='otchets'),
    path('add/', mainapp.add_abit, name='add'),
    path('edit/', mainapp.edit_abit, name='edit'),
    path('delete/', mainapp.main, name='main'),
    # path('delete/', mainapp.delete_abit, name='delete'),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

priem22/mainapp/models.py
from django.db import models


class Specialization(models.Model):
    name = models.CharField(
        verbose_name='Название специальности',
        max_length=120,
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание специальности',
        blank=True,
    )
    limit_bg = models.IntegerField(
        verbose_name='Размер набора на бюджет',
        default=None
    )
    limit_pay = models.IntegerField(
        verbose_name='Размер набора на внебюджет',
        default=None
    )
    is_active = models.BooleanField(
        verbose_name='активна',
        default=True
    )

    def __str__(self):
        return self.name


class Abiturient(models.Model):
    lastname = models.CharField(
        verbose_name='Фамилия',
        max_length=32,
        unique=False
    )
    firstname = models.CharField(
        verbose_name='Имя',
        max_length=32,
        unique=False
    )
    midlename = models.CharField(
        verbose_name='Отчество',
        max_length=32,
        unique=False,
        blank=True
    )
    birthday = models.DateField(
        verbose_name='Дата рождения',
        unique=False
    )
    avg_ball = models.FloatField(
        verbose_name='Средний бал',
        default=None
    )
    special = models.ForeignKey(
        Specialization,
        on_delete=models.CASCADE
    )

    created = models.DateTimeField(
        auto_now=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return f'{self.lastname} {self.firstname} {self.midlename}'

priem22/mainapp/views.py
from django.shortcuts import render
from datetime import date

from mainapp.models import Abiturient


def main(request):
    title = 'Главная'
    abit = Abiturient.objects.all()
    len_items = len(abit)
    context = {
        'title': title,
    }
    return render(request, 'mainapp/index.html', context)


def abit(request):
    title = 'Абитуриент'

    abit = Abiturient.objects.all()
    len_items = len(abit)

    today_item = 0

    for item in abit:
        now = item.created.date()
        # print(now.day, '  ', date.today().day)
        if now.day == date.today().day:
            today_item += 1

    # print(len_items)
    context = {
        'title': title,
        'today_item': today_item,
        'items_list': abit,
        'len_items': len_items,
    }
    return render(request, 'mainapp/abit.html', context)


def otchets(request):
    title = 'Отчеты'
    context = {
        'title': title,
        'links_menu': '',
        'category': '',
        'products': '',
    }
    return render(request, 'mainapp/otchets.html', context)


def add_abit(request):
    title = 'Добавление нового абитуриента'
    context = {
        'title': title,
        'links_menu': '',
        'category': '',
        'products': '',
    }
    return render(request, 'mainapp/add_abit.html', context)


def edit_abit(request):
    title = 'Редактирование информации об абитуриенте'
    context = {
        'title': title,
        'links_menu': '',
        'category': '',
        'products': '',
    }
    return render(request, 'mainapp/edit_abit.html', context)


def delete_abit(request):
    title = 'Удаление абитуриента'
    # context = {
    #     'title': title,
    #     'links_menu': '',
    #     'category': '',
    #     'products': '',
    # }
    # return render(request, 'mainapp/edit_abit.html', context)

priem22/mainapp/templates/mainapp/includes/inc_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!--    <a class="navbar-brand" href="#">Навигация</a>-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'main' %}">Главная</a>
                <a class="nav-link" href="{% url 'abit' %}">Абитуриенты</a>
                <a class="nav-link" href="{% url 'otchets' %}">Отчеты</a>
                <a class="nav-link" href="{% url 'add' %}">Добавить</a>
                {% if user.is_authenticated %}
                <li class="nav-link" >
                    <a href="{% url 'auth:edit' %}">
                        {{ user.username|default:'Пользователь' }}
                    </a>
                </li>
                {% endif %}
                <li class="nav-link" >
                    {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">выйти</a>
                    {% else %}
                    <a href="{% url 'auth:login' %}">войти</a>
                    {% endif %}
                </li>
                <!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
            </div>
        </div>
    </div>
</nav>